export const POI_POLL = 0;
export const WHITELIST_POLL = 1;

export const TESTNET_POLL_INDEX = "TAVGTNCVGALLUPZC4JTLKR2WX25RQM2QOK5BHBKC";
export const MAINNET_POLL_INDEX = "NAZN26HYB7C5HVYVJ4SL3KBTDT773NZBAOMGRFZB";
